# Generated by Django 5.1.7 on 2025-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200),
        ),
        migrations.AlterField(
            model_name='punto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
