# Generated by Django 5.1.7 on 2025-03-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_pregunta_opciones_pregunta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='opciones',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
