# Generated by Django 5.1.7 on 2025-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_alter_pregunta_opciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='opciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
