# Generated by Django 5.1.7 on 2025-03-20 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0006_alter_pregunta_opciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='opciones',
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapp.pregunta')),
            ],
        ),
    ]
