# Generated by Django 5.1.7 on 2025-03-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0007_remove_pregunta_opciones_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('verdadero_falso', 'Verdadero/Falso'), ('opcion_multiple', 'Opción Múltiple'), ('foto', 'Foto')], default='texto', max_length=20),
        ),
    ]
