# Generated by Django 5.1.7 on 2025-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0008_pregunta_foto_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='mostrar_como_radio',
            field=models.BooleanField(default=False),
        ),
    ]
