# Generated by Django 5.1.7 on 2025-03-21 19:23

import mapapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0009_pregunta_mostrar_como_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=mapapp.models.content_file_name_adjunto),
        ),
    ]
