# Generated by Django 5.1.7 on 2025-03-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0010_alter_pregunta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='rango_maximo',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='rango_minimo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('verdadero_falso', 'Verdadero/Falso'), ('opcion_multiple', 'Opción Múltiple'), ('foto', 'Foto'), ('valoracion', 'Valoración')], default='texto', max_length=20),
        ),
    ]
