# Generated by Django 5.1.7 on 2025-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0011_pregunta_rango_maximo_pregunta_rango_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
