# Generated by Django 5.1.7 on 2025-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0012_punto_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_formulario/')),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('verdadero_falso', 'Verdadero/Falso'), ('opcion_multiple', 'Opción Múltiple'), ('foto', 'Foto'), ('valoracion', 'Valoración'), ('portada', 'portada')], default='texto', max_length=20),
        ),
    ]
