# Generated by Django 5.1.7 on 2025-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0013_nuevoformulario_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto',
            name='portada',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('verdadero_falso', 'Verdadero/Falso'), ('opcion_multiple', 'Opción Múltiple'), ('foto', 'Foto'), ('valoracion', 'Valoración')], default='texto', max_length=20),
        ),
    ]
