# Generated by Django 5.1.7 on 2025-03-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0014_remove_punto_portada_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas_fotos/'),
        ),
        migrations.CreateModel(
            name='ImagenRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_respuestas/')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapp.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='respuesta',
            name='imagen_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapapp.imagenrespuesta'),
        ),
    ]
