# Generated by Django 5.1.7 on 2025-03-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0015_alter_pregunta_foto_imagenrespuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenrespuesta',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='imagenrespuesta',
            name='punto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapapp.punto'),
        ),
    ]
