# Generated by Django 5.1.7 on 2025-04-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0017_formulario_pregunta_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
