# Generated by Django 5.1.7 on 2025-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0018_alter_formulario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un formulario con este nombre. Por favor, elige otro.'}, max_length=100, unique=True),
        ),
    ]
