# Generated by Django 5.1.7 on 2025-04-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0019_alter_formulario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='formularios_imagenes/'),
        ),
    ]
