# Generated by Django 5.1.7 on 2025-04-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0020_formulario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='permitir_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='rango_maximo',
            field=models.IntegerField(default=5),
        ),
    ]
