# Generated by Django 5.1.7 on 2025-04-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0021_pregunta_permitir_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Subtítulo o aclaración de la pregunta', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Sugerencia para el input (solo tipo texto)', max_length=255, null=True),
        ),
    ]
