# Generated by Django 5.1.7 on 2025-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0022_pregunta_descripcion_pregunta_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='descripcion_align',
            field=models.CharField(default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='descripcion_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='descripcion_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='formulario',
            name='descripcion_font',
            field=models.CharField(default="'Inter',sans-serif", max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='descripcion_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='descripcion_underline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_align',
            field=models.CharField(default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_font',
            field=models.CharField(default="'Inter',sans-serif", max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_underline',
            field=models.BooleanField(default=False),
        ),
    ]
