# Generated by Django 5.1.7 on 2025-04-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0023_formulario_descripcion_align_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='obligatorio',
            field=models.BooleanField(default=False),
        ),
    ]
