# Generated by Django 5.1.7 on 2025-05-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0024_alter_formulario_options_pregunta_obligatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='texto_boton_enviar',
            field=models.CharField(default='Enviar', max_length=50),
        ),
    ]
