# Generated by Django 5.1.7 on 2025-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0025_formulario_texto_boton_enviar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('verdadero_falso', 'Verdadero/Falso'), ('opcion_multiple', 'Opción Múltiple'), ('foto', 'Foto'), ('valoracion', 'Valoración'), ('mapa', 'Mapa')], default='texto', max_length=20),
        ),
    ]
