# Generated by Django 5.1.7 on 2025-05-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0026_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='punto',
            name='nombre',
        ),
    ]
