# Generated by Copilot on 2025-05-25
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('mapapp', '0026_alter_pregunta_tipo'),
    ]
    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen_original',
            field=models.ImageField(upload_to='formularios_imagenes/originales/', null=True, blank=True),
        ),
    ]
