# Generated by Django 5.1.7 on 2025-05-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0027_remove_punto_direccion_remove_punto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fecha_tipo',
            field=models.CharField(choices=[('envio', 'Fecha de envío'), ('usuario', 'Fecha elegida')], default='envio', max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('verdadero_falso', 'Verdadero/Falso'), ('opcion_multiple', 'Opción Múltiple'), ('foto', 'Foto'), ('valoracion', 'Valoración'), ('mapa', 'Mapa'), ('fecha', 'Fecha')], default='texto', max_length=20),
        ),
    ]
