# Generated by Django 5.1.7 on 2025-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0029_alter_pregunta_options_pregunta_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='descripcion',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='descripcion_align',
            new_name='subtitulo_align',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='descripcion_bold',
            new_name='subtitulo_bold',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='descripcion_color',
            new_name='subtitulo_color',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='descripcion_font',
            new_name='subtitulo_font',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='descripcion_italic',
            new_name='subtitulo_italic',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='descripcion_underline',
            new_name='subtitulo_underline',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre_align',
            new_name='titulo_align',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre_bold',
            new_name='titulo_bold',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre_color',
            new_name='titulo_color',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre_font',
            new_name='titulo_font',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre_italic',
            new_name='titulo_italic',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='nombre_underline',
            new_name='titulo_underline',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='formulario',
            name='titulo',
            field=models.CharField(default='Sin titulo', error_messages={'unique': 'Ya existe un formulario con este título. Por favor, elige otro.'}, max_length=100),
            preserve_default=False,
        ),
    ]
