# Generated by Django 5.1.7 on 2025-05-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0030_rename_descripcion_formulario_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(default='Sin nombre', error_messages={'unique': 'Ya existe un formulario con este Nombre. Por favor, elige otro.'}, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
