# Generated by Django 5.1.7 on 2025-05-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0031_formulario_descripcion_formulario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='tema_color',
            field=models.CharField(default='#e8e8e8', max_length=7),
        ),
    ]
