# Generated by Django 5.1.7 on 2025-05-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0027_formulario_imagen_original'),
        ('mapapp', '0032_formulario_tema_color'),
    ]

    operations = [
    ]
