# Generated by Django 5.1.7 on 2025-05-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0034_usuario_remove_formulario_imagen_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='imagen_original',
        ),
    ]
