# Generated by Django 5.1.7 on 2025-06-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0026_formulario_permitir_volver_a_contestar'),
        ('mapapp', '0035_remove_formulario_imagen_original'),
    ]

    operations = [
    ]
