# Generated by Django 5.1.7 on 2025-06-09 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0036_merge_20250605_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='mapa_tipo',
            field=models.CharField(choices=[('punto', 'Punto'), ('linea', 'Línea'), ('poligono', 'Polígono')], default='punto', help_text='Tipo de selección de área en preguntas tipo mapa', max_length=10),
        ),
        migrations.CreateModel(
            name='Geometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('punto', 'Punto'), ('linea', 'Línea'), ('poligono', 'Polígono')], max_length=10)),
                ('coordenadas', models.TextField(help_text='Coordenadas en formato JSON: punto=[lat,lng], linea/poligono=[[lat,lng],...]')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometrias', to='mapapp.pregunta')),
                ('punto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapapp.punto')),
            ],
        ),
    ]
