# Generated by Django 5.1.7 on 2025-06-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0038_formulario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='formulario',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento al que pertenece el formulario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapapp.departamento'),
        ),
    ]
