# Generated by Django 5.1.7 on 2025-06-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0040_departamento_poblar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioRespondidoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapp.formulario')),
            ],
        ),
    ]
