# Generated by Django 5.1.7 on 2025-06-13 02:24

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0041_formulariorespondidoip'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
