# Generated by Django 5.1.5 on 2025-06-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0042_fake_pregunta_dependiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='pregunta_dependiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_dependientes', to='mapapp.pregunta'),
        ),
    ]
