# Generated by Django 3.2.15 on 2025-06-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0042_fake_pregunta_dependiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='pregunta_dependiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_dependientes', to='mapapp.pregunta'),
        ),
    ]
