# Generated by Django 5.2.5 on 2025-08-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0043_pregunta_pregunta_dependiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='subtitulo_fontSize',
            field=models.CharField(default='16px', max_length=10),
        ),
    ]
