# Generated by Django 3.2.15 on 2025-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0043_pregunta_pregunta_dependiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='subtitulo_fontSize',
            field=models.CharField(default='16px', max_length=10),
        ),
    ]
