# Generated by Django 3.2.15 on 2025-07-31 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0044_formulario_subtitulo_fontsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, help_text='Texto del formulario', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del formulario', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_texto', to='mapapp.formulario')),
            ],
            options={
                'verbose_name': 'Formulario Texto',
                'verbose_name_plural': 'Formularios Texto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
