# Generated by Django 3.2.15 on 2025-08-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0045_formulariotexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariotexto',
            name='descripcion_align',
            field=models.CharField(default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='descripcion_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='descripcion_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='descripcion_font',
            field=models.CharField(default="'Inter',sans-serif", max_length=100),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='descripcion_fontSize',
            field=models.CharField(default='16px', max_length=10),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='descripcion_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='descripcion_underline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='texto_align',
            field=models.CharField(default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='texto_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='texto_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='texto_font',
            field=models.CharField(default="'Inter',sans-serif", max_length=100),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='texto_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulariotexto',
            name='texto_underline',
            field=models.BooleanField(default=False),
        ),
    ]
