# Generated by Django 5.1.6 on 2025-02-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='apoyo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='apoyo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.apoyo'),
        ),
    ]
