# Generated by Django 5.1.6 on 2025-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_tarea_apoyo_tarea_apoyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='apoyo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='apoyo',
            field=models.ManyToManyField(blank=True, to='tareas.apoyo'),
        ),
    ]
