# Generated by Django 3.2.15 on 2025-07-04 14:21

import archivos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archivos', '0003_acceso_pagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privada', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=255)),
                ('carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='archivos.carpeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=archivos.models.ruta_archivo_completa),
        ),
        migrations.AddField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='archivos.carpeta'),
        ),
        migrations.CreateModel(
            name='PermisoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[('lectura', 'Solo lectura'), ('escritura', 'Lectura y escritura'), ('propietario', 'Propietario')], max_length=50)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.carpeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('carpeta', 'usuario')},
            },
        ),
    ]
